// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbbkpvleuyaftlgoxqea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiYmtwdmxldXlhZnRsZ294cWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTUyMTgsImV4cCI6MjA2NjA5MTIxOH0.Ag2ZgPl4Mjxz4QIYOZgNpp37qqTCr9G0xZ1ZrvCj9fY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);