// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydtkmvnzaqncuytxqnwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkdGttdm56YXFuY3V5dHhxbndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTM0NDIsImV4cCI6MjA2NjUyOTQ0Mn0.9QRRZ6htk6RivrF-DHddG_2jUNRVo02KMMSdHY01ruc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);